name: Mirror NWS Hazard Map

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:

jobs:
  update-map:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Hazard Map
      run: |
        curl -o hazardmap.png https://forecast.weather.gov/wwamap/png/TSA.png

 - name: Commit new map
  run: |
    git config user.name "Fat Kevin Weather Bot"
    git config user.email "fatkevinweather@example.com"
    git add hazardmap.png
    git commit -m "Auto-update hazard map" || echo "No changes to commit"
    git push

